import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { StatCard, RiskBadge, Card, SectionHeader, LoadingSpinner } from '../../components/UIComponents';
import { ClipboardList, CheckCircle, Clock, TrendingUp, Sparkles } from 'lucide-react';
import api from '../../api/client';
import {jwtDecode} from 'jwt-decode';

function getStudentId() {
  const token = localStorage.getItem('token');
  if (!token) return null;
  try {
    return jwtDecode(token).student_id;
  } catch { return null; }
}

export default function StudentHome() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  // We need to get the actual student's MongoDB _id first
  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        const meRes = await api.get('/auth/me');
        if (!meRes || !meRes.data) throw new Error("Could not fetch user profile");
        
        const sid = meRes.data._id?.$oid || meRes.data._id || meRes.data.id || meRes.data.student_id;
        if (!sid) {
          console.warn('Student ID not found in profile');
          setLoading(false);
          return;
        }
        
        const dashRes = await api.get(`/student/dashboard/${sid}`);
        if (dashRes.data) {
          setData({ ...dashRes.data, studentId: sid });
        }
      } catch (err) {
        console.error('Dashboard fetch failed', err);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboard();
  }, []);

  if (loading) return <div className="p-8"><LoadingSpinner /></div>;

  const student = data?.student;
  const quizzes = data?.assigned_quizzes || [];
  const attempts = data?.attempts || [];
  const completedIds = new Set(attempts.map(a => a.quiz_id));
  const pending = quizzes.filter(q => !completedIds.has(q._id?.$oid || q._id));

  return (
    <div className="p-8">
      {/* Welcome Header */}
      <div className="mb-8 p-6 rounded-2xl bg-gradient-to-r from-primary-600 to-blue-700 text-white shadow-xl shadow-primary-500/20">
        <div className="flex items-start justify-between">
          <div>
            <p className="text-primary-100 text-sm font-medium mb-1">Welcome back 👋</p>
            <h1 className="text-2xl font-bold mb-2">{student?.username || user?.username}</h1>
            <div className="flex items-center gap-3 flex-wrap">
              <span className="text-primary-100 text-sm">Overall Average: <strong className="text-white">{((student?.overall_average) ?? 0).toFixed(1)}%</strong></span>
              <RiskBadge level={student?.risk_level || 'low'} />
            </div>
          </div>
          <TrendingUp className="w-12 h-12 text-primary-200 opacity-60" />
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        <StatCard icon={ClipboardList} label="Assigned Quizzes" value={quizzes.length} color="blue" />
        <StatCard icon={CheckCircle} label="Completed" value={completedIds.size} color="green" />
        <StatCard icon={Clock} label="Pending" value={pending.length} color="amber" />
      </div>

      {/* Topic Information & Summary */}
      {data?.assigned_topic && (
        <Card className="p-6 mb-6 border-l-4 border-indigo-500 shadow-sm relative overflow-hidden bg-white/40">
           <div className="absolute top-0 right-0 p-3 opacity-10">
            <ClipboardList className="w-12 h-12 text-indigo-900" />
           </div>
           <div className="relative z-10">
            <h3 className="text-sm font-bold text-indigo-700 uppercase tracking-wider mb-2">Current Assigned Topic</h3>
            <p className="text-2xl font-black text-gray-900 mb-4">{data.assigned_topic}</p>
            
            {data.topic_summary && (
              <div className="mt-4 p-4 bg-indigo-50/50 rounded-xl border border-indigo-100">
                <div className="flex items-center gap-2 mb-2 text-indigo-800">
                  <Sparkles className="w-4 h-4" />
                  <span className="text-xs font-bold uppercase tracking-widest">Topic Summary (Generated by AI)</span>
                </div>
                <p className="text-gray-700 text-sm leading-relaxed">{data.topic_summary}</p>
              </div>
            )}
           </div>
        </Card>
      )}

      {/* AI Performance Mentoring */}
      {data?.performance_summary && (
        <Card className="p-6 mb-8 border-l-4 border-emerald-500 bg-emerald-50/20 backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-2 text-emerald-800">
            <TrendingUp className="w-4 h-4" />
            <h3 className="text-sm font-bold uppercase tracking-wider">AI Performance Report</h3>
          </div>
          <p className="text-gray-700 text-sm leading-relaxed italic">"{data.performance_summary}"</p>
        </Card>
      )}

      {/* Pending Quizzes */}
      <Card className="p-6">
        <SectionHeader title="Pending Quizzes" subtitle="Complete these before the deadline" />
        {pending.length === 0 ? (
          <div className="text-center py-10">
            <CheckCircle className="w-12 h-12 text-emerald-300 mx-auto mb-3" />
            <p className="text-gray-500 font-medium">All caught up! No pending quizzes.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {pending.map((q, i) => {
              const qid = q._id?.$oid || q._id;
              const deadline = q.deadline ? new Date(q.deadline) : null;
              const isOverdue = deadline && deadline < new Date();
              return (
                <div key={i} className="border border-gray-100 rounded-xl p-4 hover:shadow-md transition-shadow">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="font-semibold text-gray-900 text-sm">{q.title || q.topic}</p>
                      <p className="text-xs text-gray-400 mt-0.5">{q.subject} • {q.topic}</p>
                    </div>
                    <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${q.difficulty === 'hard' ? 'bg-red-50 text-red-600' : q.difficulty === 'medium' ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'}`}>
                      {q.difficulty}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <p className={`text-xs ${isOverdue ? 'text-red-500 font-medium' : 'text-gray-400'}`}>
                      {deadline ? (isOverdue ? '⚠ Overdue: ' : 'Due: ') + deadline.toLocaleDateString() : 'No deadline'}
                    </p>
                    <Link to={`/quiz/${qid}`}
                      className="text-xs font-semibold text-white bg-primary-600 hover:bg-primary-700 px-3 py-1.5 rounded-lg transition-colors">
                      Attempt →
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </div>
  );
}
