import React, { useState, useEffect } from 'react';
import { Card, SectionHeader, LoadingSpinner } from '../../components/UIComponents';
import api from '../../api/client';
import { ClipboardList, Loader2, CheckCircle } from 'lucide-react';

export default function AssignQuiz() {
  const [students, setStudents] = useState([]);
  const [form, setForm] = useState({
    subject: '', topic: '', difficulty: 'medium',
    number_of_questions: 5, deadline: '', assigned_to: []
  });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    console.log('ASSIGN_QUIZ: Fetching students...');
    api.get('/admin/students')
      .then(res => {
        console.log('ASSIGN_QUIZ: Students received:', res.data);
        setStudents(res.data);
      })
      .catch(err => {
        console.error('ASSIGN_QUIZ: Fetch error:', err);
        setError(err.response?.data?.detail || 'Failed to load students for assignment.');
      });
  }, []);

  const toggleStudent = (id) => {
    setForm(prev => ({
      ...prev,
      assigned_to: prev.assigned_to.includes(id)
        ? prev.assigned_to.filter(s => s !== id)
        : [...prev.assigned_to, id]
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (form.assigned_to.length === 0) { setError('Please select at least one student.'); return; }
    setLoading(true); setError(''); setSuccess(false);
    try {
      await api.post('/admin/assign-quiz', form);
      setSuccess(true);
      setForm({ subject: '', topic: '', difficulty: 'medium', number_of_questions: 5, deadline: '', assigned_to: [] });
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to assign quiz. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-8">
      <SectionHeader title="Assign Quiz" subtitle="AI will automatically generate quiz questions based on your inputs" />
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Quiz Config */}
        <div className="lg:col-span-2">
          <Card className="p-6">
            {success && (
              <div className="mb-5 p-4 bg-emerald-50 border border-emerald-200 text-emerald-700 rounded-xl flex items-center gap-3">
                <CheckCircle className="w-5 h-5 shrink-0" />
                <span>Quiz successfully generated by AI and assigned to students!</span>
              </div>
            )}
            {error && (
              <div className="mb-5 p-4 bg-red-50 border border-red-200 text-red-600 rounded-xl text-sm">{error}</div>
            )}
            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Subject *</label>
                  <input type="text" value={form.subject} onChange={e => setForm({...form, subject: e.target.value})}
                    className="input-field" placeholder="e.g. Mathematics" required />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Topic *</label>
                  <input type="text" value={form.topic} onChange={e => setForm({...form, topic: e.target.value})}
                    className="input-field" placeholder="e.g. Quadratic Equations" required />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Difficulty</label>
                  <select value={form.difficulty} onChange={e => setForm({...form, difficulty: e.target.value})} className="input-field">
                    <option value="easy">Easy</option>
                    <option value="medium">Medium</option>
                    <option value="hard">Hard</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">No. of Questions</label>
                  <input type="number" min="3" max="20" value={form.number_of_questions} onChange={e => setForm({...form, number_of_questions: parseInt(e.target.value)})}
                    className="input-field" />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Deadline *</label>
                <input type="datetime-local" value={form.deadline} onChange={e => setForm({...form, deadline: e.target.value})}
                  className="input-field" required />
              </div>
              <button type="submit" disabled={loading}
                className="w-full btn-primary flex items-center justify-center gap-2 py-3 text-base">
                {loading ? (
                  <><Loader2 className="w-5 h-5 animate-spin" />AI is generating Quiz and Summary...</>
                ) : (
                  <><ClipboardList className="w-5 h-5" />Generate & Assign Topic Content</>
                )}
              </button>
            </form>
          </Card>
        </div>
        {/* Student Selection */}
        <div>
          <Card className="p-5">
            <h3 className="font-semibold text-gray-900 mb-4">Select Students ({form.assigned_to.length} selected)</h3>
            {students.length === 0 ? (
              <p className="text-gray-400 text-sm text-center py-6">No students registered yet.</p>
            ) : (
              <div className="space-y-2 max-h-96 overflow-y-auto pr-1">
                {students.map(s => {
                  // Ensure we use a consistent string ID for selection
                  const sid = s.id || s._id;
                  const isSelected = form.assigned_to.includes(sid);
                  return (
                    <button key={sid} type="button" onClick={() => toggleStudent(sid)}
                      className={`w-full flex items-center gap-3 p-3 rounded-xl border-2 text-left transition-all duration-150 ${isSelected ? 'border-primary-500 bg-primary-50' : 'border-gray-100 hover:border-gray-200 bg-white'}`}>
                      <div className="w-7 h-7 rounded-full bg-primary-100 text-primary-600 flex items-center justify-center text-xs font-bold uppercase shrink-0">
                        {s.username?.[0]}
                      </div>
                      <div className="overflow-hidden">
                        <p className="text-sm font-medium text-gray-900 truncate">{s.username}</p>
                        <p className="text-xs text-gray-400 truncate">{s.email}</p>
                      </div>
                      {isSelected && <CheckCircle className="w-4 h-4 text-primary-500 ml-auto shrink-0" />}
                    </button>
                  );
                })}
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
